// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_CwqCm_FWJ_dNuHJTl0XJpvgVF7KgEQ8',
    appId: '1:794308607821:web:ab217e762e012119610104',
    messagingSenderId: '794308607821',
    projectId: 'georgenabil-4954e',
    authDomain: 'georgenabil-4954e.firebaseapp.com',
    databaseURL: 'https://georgenabil-4954e-default-rtdb.firebaseio.com',
    storageBucket: 'georgenabil-4954e.firebasestorage.app',
    measurementId: 'G-JXFH4S8ZBL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDD0Hg6qYIP3BUjIAY_fKLZaJ6-5J_zLu0',
    appId: '1:794308607821:android:ec61de7632e21d44610104',
    messagingSenderId: '794308607821',
    projectId: 'georgenabil-4954e',
    databaseURL: 'https://georgenabil-4954e-default-rtdb.firebaseio.com',
    storageBucket: 'georgenabil-4954e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfez5VcCLZgJJLsw3fP9muVu2l_kxk4m0',
    appId: '1:794308607821:ios:5d83f63d1ae30fe5610104',
    messagingSenderId: '794308607821',
    projectId: 'georgenabil-4954e',
    databaseURL: 'https://georgenabil-4954e-default-rtdb.firebaseio.com',
    storageBucket: 'georgenabil-4954e.firebasestorage.app',
    iosBundleId: 'com.example.georgenabil',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfez5VcCLZgJJLsw3fP9muVu2l_kxk4m0',
    appId: '1:794308607821:ios:5d83f63d1ae30fe5610104',
    messagingSenderId: '794308607821',
    projectId: 'georgenabil-4954e',
    databaseURL: 'https://georgenabil-4954e-default-rtdb.firebaseio.com',
    storageBucket: 'georgenabil-4954e.firebasestorage.app',
    iosBundleId: 'com.example.georgenabil',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_CwqCm_FWJ_dNuHJTl0XJpvgVF7KgEQ8',
    appId: '1:794308607821:web:1bafd75c0d610c1c610104',
    messagingSenderId: '794308607821',
    projectId: 'georgenabil-4954e',
    authDomain: 'georgenabil-4954e.firebaseapp.com',
    databaseURL: 'https://georgenabil-4954e-default-rtdb.firebaseio.com',
    storageBucket: 'georgenabil-4954e.firebasestorage.app',
    measurementId: 'G-RWFDZBGB9J',
  );
}
